"use client";

import { useMemo } from "react";
import { useStore } from "@/context/store";
import {
  exportRegisterExcel,
  exportRegisterPDF,
  exportSummaryExcel,
  exportSummaryPDF,
} from "@/lib/exports";
import { daysUntil, formatDateAU } from "@/lib/helpers";
import type { Asset } from "@/lib/types";
import { Icon } from "./ui";

function ReportRow({ label, value, color }: { label: React.ReactNode; value: React.ReactNode; color?: string }) {
  return (
    <div className="report-row">
      <span>{label}</span>
      <strong style={color ? { color } : undefined}>{value}</strong>
    </div>
  );
}

export default function ReportView() {
  const { assets, locations, company, checkData, toast } = useStore();

  const { overdue, dueSoon } = useMemo(() => {
    const isOverdue = (a: Asset) => {
      const d = daysUntil(a.complianceDate);
      return d !== null && d < 0;
    };
    const isDueSoon = (a: Asset) => {
      const d = daysUntil(a.complianceDate);
      return d !== null && d >= 0 && d <= 30;
    };
    return {
      overdue: assets.filter(isOverdue),
      dueSoon: assets.filter(isDueSoon),
    };
  }, [assets]);

  const guard = (p: Promise<unknown>) =>
    p.catch((e) => toast("Export failed: " + (e as Error).message, "error"));

  const shareReport = () => {
    const today = new Date();
    let text = `RigTrak Report — ${today.toLocaleDateString("en-AU", {
      day: "numeric",
      month: "long",
      year: "numeric",
    })}\n`;
    text += `━━━━━━━━━━━━━━━━━━━━━━\n`;
    text += `Total Assets: ${assets.length}\n`;
    text += `Active: ${assets.filter((a) => a.status === "Active").length}\n`;
    text += `Quarantined: ${assets.filter((a) => a.status === "Quarantine").length}\n`;
    text += `Condemned: ${assets.filter((a) => a.status === "Condemned").length}\n`;
    if (overdue.length) {
      text += `\n⚠ COMPLIANCE OVERDUE (${overdue.length}):\n`;
      overdue.forEach((a) => {
        text += `• ${a.name || "Unnamed"} (${a.location || "No location"}) — ${formatDateAU(a.complianceDate)}\n`;
      });
    }
    if (dueSoon.length) {
      text += `\n⏳ DUE WITHIN 30 DAYS (${dueSoon.length}):\n`;
      dueSoon.forEach((a) => {
        text += `• ${a.name || "Unnamed"} (${a.location || "No location"}) — ${formatDateAU(a.complianceDate)}\n`;
      });
    }
    if (checkData) {
      text += `\nLAST INVENTORY CHECK:\n`;
      text += `Location: ${checkData.locationName}\n`;
      text += `Found: ${checkData.found.length} · Missing: ${checkData.missing.length}\n`;
      if (checkData.missing.length) {
        text += `Missing items:\n`;
        checkData.missing.forEach((a) => {
          text += `• ${a.name}\n`;
        });
      }
    }
    text += `\nGenerated by RigTrak`;

    if (navigator.share) {
      navigator.share({ title: "RigTrak Report", text }).catch(() => {});
    } else {
      navigator.clipboard
        .writeText(text)
        .then(() => toast("Report copied to clipboard ✓", "success"))
        .catch(() => toast("Could not copy — try on mobile", "error"));
    }
  };

  return (
    <div>
      <div className="report-section">
        <h3>
          Summary — {new Date().toLocaleDateString("en-AU", { day: "numeric", month: "long", year: "numeric" })}
        </h3>
        <ReportRow label="Total Assets" value={assets.length} />
        <ReportRow
          label="Active"
          value={assets.filter((a) => a.status === "Active").length}
          color="var(--green)"
        />
        <ReportRow
          label="Quarantined"
          value={assets.filter((a) => a.status === "Quarantine").length}
          color="var(--yellow)"
        />
        <ReportRow
          label="Condemned"
          value={assets.filter((a) => a.status === "Condemned").length}
          color="var(--red)"
        />
        <ReportRow
          label="Unregistered"
          value={assets.filter((a) => !a.name || a.status === "Unregistered").length}
          color="var(--dim)"
        />
      </div>

      {overdue.length > 0 && (
        <div className="report-section">
          <h3>⚠ Compliance Overdue ({overdue.length})</h3>
          {overdue.map((a) => (
            <ReportRow
              key={a.id}
              label={
                <>
                  {a.name || "Unnamed"} <span style={{ color: "var(--dim)", fontSize: 12 }}>{a.location}</span>
                </>
              }
              value={formatDateAU(a.complianceDate)}
              color="var(--red)"
            />
          ))}
        </div>
      )}

      {dueSoon.length > 0 && (
        <div className="report-section">
          <h3>⏳ Due Within 30 Days ({dueSoon.length})</h3>
          {dueSoon.map((a) => (
            <ReportRow
              key={a.id}
              label={
                <>
                  {a.name || "Unnamed"} <span style={{ color: "var(--dim)", fontSize: 12 }}>{a.location}</span>
                </>
              }
              value={formatDateAU(a.complianceDate)}
              color="var(--yellow)"
            />
          ))}
        </div>
      )}

      <div className="report-section">
        <h3>Assets by Location</h3>
        {locations.map((l) => {
          const count = assets.filter((a) => a.location === l.name && a.name).length;
          return count > 0 ? <ReportRow key={l.id} label={l.name} value={count} /> : null;
        })}
      </div>

      <div className="report-section">
        <h3>Summary Report</h3>
        <p style={{ fontSize: 13, color: "var(--dim)", marginBottom: 12, lineHeight: 1.5 }}>
          Compliance overview — totals, overdue and due-soon items.
        </p>
        <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
          <button className="btn-secondary" style={{ flex: 1 }} onClick={shareReport}>
            <Icon name="share" /> Share
          </button>
          <button
            className="btn-secondary"
            style={{ flex: 1 }}
            onClick={() => guard(exportSummaryPDF(assets, company))}
          >
            <Icon name="file-type-pdf" /> PDF
          </button>
          <button
            className="btn-secondary"
            style={{ flex: 1 }}
            onClick={() => guard(exportSummaryExcel(assets, company))}
          >
            <Icon name="file-spreadsheet" /> Excel
          </button>
        </div>
      </div>

      <div className="report-section">
        <h3>Full Asset Register</h3>
        <p style={{ fontSize: 13, color: "var(--dim)", marginBottom: 12, lineHeight: 1.5 }}>
          Every asset with full details — suitable for client handover.
        </p>
        <div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>
          <button
            className="btn-primary"
            style={{ flex: 1 }}
            onClick={() => guard(exportRegisterPDF(assets, company))}
          >
            <Icon name="file-type-pdf" /> PDF
          </button>
          <button
            className="btn-primary"
            style={{ flex: 1 }}
            onClick={() => guard(exportRegisterExcel(assets, company))}
          >
            <Icon name="file-spreadsheet" /> Excel
          </button>
        </div>
      </div>
    </div>
  );
}
